### ISSUE TITLE
TypeError: get_cu_file_str() missing 1 required positional argument: 'idtype'

### ISSUE THREAD

**Issue by xuzhenqi** [flashinfer-ai/flashinfer#222]
Reproduce steps for current head `dd88deaed6aea4fec49eec721f62dd6b53ffbd5b`:
```shell
mkdir build
cd build
cmake ..
build -j16
```

Error log:
```
[  4%] Generating additional source file /home/luban/flashinfer/src/generated/batch_padded_decode_group_6_head_128_layout_1_posenc_2_dtypein_e4m3_dtypeout_e4m3.cu
Traceback (most recent call last):
  File "/home/luban/flashinfer/python/generate_batch_paged_prefill_inst.py", line 92, in <module>
    f.write(get_cu_file_str(*match.groups()))
TypeError: get_cu_file_str() missing 1 required positional argument: 'idtype'
Traceback (most recent call last):
  File "/home/luban/flashinfer/python/generate_batch_paged_prefill_inst.py", line 92, in <module>
    f.write(get_cu_file_str(*match.groups()))
TypeError: get_cu_file_str() missing 1 required positional argument: 'idtype'
```
Fp8 kernels have different filenames, and do not contain idtype.

**Comment by xuzhenqi** [comment]
Already fixed in main branch.
