### ISSUE TITLE
Circular import error when importing built-from-source flashinfer

### ISSUE THREAD

**Issue by vedantroy** [flashinfer-ai/flashinfer#248]
Tried to compile commit `3b3ce057c935730e15da67c6879c90cbe759cbf7f` from source with `pip install .`

When importing flashinfer, I get the error:

```
>>> import flashinfer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/flashinfer/python/flashinfer/__init__.py", line 17, in <module>
    from .decode import (
  File "/tmp/flashinfer/python/flashinfer/decode.py", line 31, in <module>
    raise e
  File "/tmp/flashinfer/python/flashinfer/decode.py", line 22, in <module>
    from . import _kernels
ImportError: cannot import name '_kernels' from partially initialized module 'flashinfer' (most likely due to a circular import) (/tmp/flashinfer/python/flashinfer/__init__.py)
```

**Comment by vedantroy** [comment]
The error goes away if I use:
```
env FLASHINFER_GROUP_SIZES=8 pip install -e .
```
