### ISSUE TITLE
Installation fails immediately: ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by Brennanzuz** [flashinfer-ai/flashinfer#316]
The installation instructions is incomplete, and causes a quick error:

```sh
git clone https://github.com/flashinfer-ai/flashinfer.git --recursive
cd flashinfer/python
python3.11 -m venv venv
source venv/bin/activate
pip install -e .
```

It returned this:

```text
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Obtaining file:///home/jovyan/flashinfer/python
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/home/jovyan/flashinfer/python/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/jovyan/flashinfer/python/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/jovyan/flashinfer/python/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-v7t0gp5t/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 458, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-v7t0gp5t/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-v7t0gp5t/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-v7t0gp5t/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-v7t0gp5t/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 28, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

How do I solve something like this?

**Comment by yzh119** [comment]
Hi @Brennanzuz , you have to install torch first if you want to use FlashInfer in python.

**Comment by Brennanzuz** [comment]
Hmm, but I have it installed on my virtual environment already though with:

```sh
source venv/bin/activate
pip install torch
pip install -e .
```

And it still returned that. Sorry if this is a newbie question

**Comment by zhyncs** [comment]
ref https://github.com/flashinfer-ai/flashinfer/blob/a23979b330b1868a6787f826d8da877bf6603b8a/scripts/run-ci-build-wheel.sh#L37-L45
